In [9]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
iris=pd.read_csv("E:/Machine Learning with Python from Scratch/Machine Learning with Python from Scratch/Source-code-Data-Analysis-L11-Pandas-Statistics-with-Pandas/statistics_data/iris.csv")
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X=iris[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=iris['Species']

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(list(set(y)))
y_encoded=le.transform(y)
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
from tensorflow.keras.utils import to_categorical
y_cat=to_categorical(y_encoded)
y_cat[0]

array([1., 0., 0.], dtype=float32)

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y_cat,test_size=0.2,random_state=42,shuffle=True)

In [21]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[120 rows x 4 columns]

In [22]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [25]:
model=Sequential([
    Dense(32,activation='relu',input_shape=(4,)),
    Dense(32,activation='relu'),
    Dense(3,activation='softmax')
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                160       
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 99        
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [29]:
model.fit(X_train,y_train,epochs=30)

Epoch 1/30
4/4 [==============================] - 0s 1ms/step - loss: 0.7283 - accuracy: 0.9417
Epoch 2/30
4/4 [==============================] - 0s 1ms/step - loss: 0.6927 - accuracy: 0.9250
Epoch 3/30
4/4 [==============================] - 0s 1ms/step - loss: 0.6620 - accuracy: 0.9333
Epoch 4/30
4/4 [==============================] - 0s 1ms/step - loss: 0.6317 - accuracy: 0.9583
Epoch 5/30
4/4 [==============================] - 0s 1ms/step - loss: 0.5999 - accuracy: 0.9583
Epoch 6/30
4/4 [==============================] - 0s 1ms/step - loss: 0.5714 - accuracy: 0.9417
Epoch 7/30
4/4 [==============================] - 0s 1ms/step - loss: 0.5431 - accuracy: 0.9417
Epoch 8/30
4/4 [==============================] - 0s 1ms/step - loss: 0.5156 - accuracy: 0.9500
Epoch 9/30
4/4 [==============================] - 0s 2ms/step - loss: 0.4902 - accuracy: 0.9667
Epoch 10/30
4/4 [==============================] - 0s 998us/step - loss: 0.4669 - accuracy: 0.9667
Epoch 11/30
4/4 [====================

In [30]:
_,accuracy=model.evaluate(X_test,y_test)
print(accuracy*100)

1/1 [==============================] - 0s 1000us/step - loss: 0.2223 - accuracy: 1.0000
100.0
